--------------------------------------------------------
--  파일이 생성됨 - 월요일-1월-13-2025
--------------------------------------------------------

--------------------------------------------------------
--  DROP TABLE Statements
--------------------------------------------------------
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE CHAT_SESSION CASCADE CONSTRAINTS;
DROP TABLE CHAT_WORKSPACE CASCADE CONSTRAINTS;
DROP TABLE DASHBOARD CASCADE CONSTRAINTS;
DROP TABLE DOC_FILE CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT CASCADE CONSTRAINTS;
DROP TABLE EMERGENCY_LOG CASCADE CONSTRAINTS;
DROP TABLE FAQ CASCADE CONSTRAINTS;
DROP TABLE MEDICAL CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MEMBER_FILES CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE NOTICE_FILES CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE REFRESH_TOKEN CASCADE CONSTRAINTS;
DROP TABLE SENIOR_PROGRAM CASCADE CONSTRAINTS;
DROP TABLE SENIOR_PROGRAM_FILE CASCADE CONSTRAINTS;



--------------------------------------------------------
--  Table: BOOK
--------------------------------------------------------
-- Create Table
CREATE TABLE BOOK (
                      BOOK_NUM         VARCHAR2(100 BYTE),
                      BOOK_TITLE       VARCHAR2(250 BYTE),
                      BOOK_CREATED_AT  TIMESTAMP (6) DEFAULT SYSDATE,
                      BOOK_UPDATED_AT  TIMESTAMP (6) DEFAULT SYSDATE,
                      BOOK_DETAIL      VARCHAR2(1000 BYTE),
                      BOOK_IMAGE       VARCHAR2(1000 BYTE),
                      BOOK_CREATED_BY  VARCHAR2(50 BYTE),
                      BOOK_UPDATED_BY  VARCHAR2(50 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN BOOK.BOOK_NUM IS '책 식별코드';
COMMENT ON COLUMN BOOK.BOOK_TITLE IS '제목';
COMMENT ON COLUMN BOOK.BOOK_CREATED_AT IS '등록날짜';
COMMENT ON COLUMN BOOK.BOOK_UPDATED_AT IS '수정날짜';
COMMENT ON COLUMN BOOK.BOOK_DETAIL IS '책 정보 첨부 파일';
COMMENT ON COLUMN BOOK.BOOK_IMAGE IS '책 표지 이미지';
COMMENT ON COLUMN BOOK.BOOK_CREATED_BY IS '등록자';
COMMENT ON COLUMN BOOK.BOOK_UPDATED_BY IS '수정자';

-- Indexes
CREATE UNIQUE INDEX PK_BOOK_NUM
    ON BOOK (BOOK_NUM)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE BOOK MODIFY (BOOK_TITLE       NOT NULL ENABLE);
ALTER TABLE BOOK MODIFY (BOOK_CREATED_AT  NOT NULL ENABLE);
ALTER TABLE BOOK MODIFY (BOOK_UPDATED_AT  NOT NULL ENABLE);
ALTER TABLE BOOK MODIFY (BOOK_DETAIL      NOT NULL ENABLE);
ALTER TABLE BOOK MODIFY (BOOK_IMAGE       NOT NULL ENABLE);
ALTER TABLE BOOK ADD CONSTRAINT PK_BOOK_NUM
    PRIMARY KEY (BOOK_NUM)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE BOOK
    ADD CONSTRAINT FK_BOOK_CREATED_BY
        FOREIGN KEY (BOOK_CREATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;
ALTER TABLE BOOK
    ADD CONSTRAINT FK_BOOK_UPDATED_BY
        FOREIGN KEY (BOOK_UPDATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;


--------------------------------------------------------
--  Table: CHAT_MESSAGE
--------------------------------------------------------
-- Create Table
CREATE TABLE CHAT_MESSAGE (
                              MSG_ID            VARCHAR2(100 BYTE),
                              MSG_SENDER_ROLE   VARCHAR2(20 BYTE),
                              MESSAGE           CLOB,
                              MSG_SENT_AT       TIMESTAMP (6),
                              MSG_SENDER_UUID   VARCHAR2(100 BYTE),
                              MSG_TYPE          CHAR(1 BYTE),
    PARENT_MSG_ID     VARCHAR2(100 BYTE),
    MSG_WORKSPACE_ID  VARCHAR2(100 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS
LOB (MESSAGE) STORE AS SECUREFILE (
    TABLESPACE USERS,
    ENABLE STORAGE IN ROW,
    CHUNK 8192,
    NOCACHE,
    LOGGING,
    NOCOMPRESS,
    KEEP_DUPLICATES,
    STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
);

-- Column Comments
COMMENT ON COLUMN CHAT_MESSAGE.MSG_ID IS '메시지 고유 ID';
COMMENT ON COLUMN CHAT_MESSAGE.MSG_SENDER_ROLE IS '누구의 메시지인지(USER/AI)';
COMMENT ON COLUMN CHAT_MESSAGE.MESSAGE IS '메시지 내용';
COMMENT ON COLUMN CHAT_MESSAGE.MSG_SENT_AT IS '메시지 생성 시간';
COMMENT ON COLUMN CHAT_MESSAGE.MSG_SENDER_UUID IS '메시지 작성자 UUID';
COMMENT ON COLUMN CHAT_MESSAGE.MSG_TYPE IS '채팅타입(T,V)';
COMMENT ON COLUMN CHAT_MESSAGE.PARENT_MSG_ID IS '부모메시지ID';
COMMENT ON COLUMN CHAT_MESSAGE.MSG_WORKSPACE_ID IS '워크스페이스 ID';

-- Indexes
CREATE UNIQUE INDEX PK_MSG_ID
    ON CHAT_MESSAGE (MSG_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE CHAT_MESSAGE MODIFY (MSG_SENDER_ROLE NOT NULL ENABLE);
ALTER TABLE CHAT_MESSAGE MODIFY (MESSAGE         NOT NULL ENABLE);
ALTER TABLE CHAT_MESSAGE MODIFY (MSG_SENT_AT     NOT NULL ENABLE);
ALTER TABLE CHAT_MESSAGE MODIFY (MSG_SENDER_UUID NOT NULL ENABLE);
ALTER TABLE CHAT_MESSAGE MODIFY (MSG_TYPE        NOT NULL ENABLE);
ALTER TABLE CHAT_MESSAGE MODIFY (MSG_WORKSPACE_ID NOT NULL ENABLE);
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT CHK_MSG_SENDER_ROLE
    CHECK (MSG_SENDER_ROLE IN ('USER','AI')) ENABLE;
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT CHK_MSG_TYPE
    CHECK (MSG_TYPE IN ('T','V')) ENABLE;
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT PK_MSG_ID
    PRIMARY KEY (MSG_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE CHAT_MESSAGE
    ADD CONSTRAINT FK_MSG_SENDER_UUID
        FOREIGN KEY (MSG_SENDER_UUID) REFERENCES MEMBER (MEM_UUID)
            ON DELETE CASCADE ENABLE;
ALTER TABLE CHAT_MESSAGE
    ADD CONSTRAINT FK_PARENT_MSG_ID
        FOREIGN KEY (PARENT_MSG_ID) REFERENCES CHAT_MESSAGE (MSG_ID)
            ON DELETE SET NULL ENABLE;
ALTER TABLE CHAT_MESSAGE
    ADD CONSTRAINT FK_MSG_WORKSPACE_ID
        FOREIGN KEY (MSG_WORKSPACE_ID) REFERENCES CHAT_WORKSPACE (WORKSPACE_ID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  Table: CHAT_SESSION
--------------------------------------------------------
-- Create Table
CREATE TABLE CHAT_SESSION (
                              SESS_ID         VARCHAR2(100 BYTE),
                              SESS_STARTED_AT TIMESTAMP (6),
                              SESS_ENDED_AT   TIMESTAMP (6),
                              IS_EMERGENCY    CHAR(1 BYTE),
    SESS_STATUS     VARCHAR2(20 BYTE),
    SESS_TOT_MSGS   NUMBER,
    SESS_TYPE       CHAR(1 BYTE),
    WORKSPACE_ID    VARCHAR2(100 BYTE),
    SESS_MEM_UUID   VARCHAR2(100 BYTE),
    LAST_UPDATED    TIMESTAMP (6) DEFAULT SYSTIMESTAMP
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN CHAT_SESSION.SESS_ID IS '세션 고유 ID';
COMMENT ON COLUMN CHAT_SESSION.SESS_STARTED_AT IS '세션 시작 시간';
COMMENT ON COLUMN CHAT_SESSION.SESS_ENDED_AT IS '세션 종료 시간';
COMMENT ON COLUMN CHAT_SESSION.IS_EMERGENCY IS '긴급상황 여부 (Y/N)';
COMMENT ON COLUMN CHAT_SESSION.SESS_STATUS IS '세션 상태 (ACTIVE, COMPLETED, ERROR, TIMEOUT)';
COMMENT ON COLUMN CHAT_SESSION.SESS_TOT_MSGS IS '메시지 총 개수';
COMMENT ON COLUMN CHAT_SESSION.SESS_TYPE IS '세션 타입 (TEXT/VOICE)';
COMMENT ON COLUMN CHAT_SESSION.WORKSPACE_ID IS '워크스페이스 고유 ID (CHAT_WORKSPACE 테이블 참조)';
COMMENT ON COLUMN CHAT_SESSION.SESS_MEM_UUID IS '세션 주인 UUID (MEMBER 테이블 참조)';
COMMENT ON COLUMN CHAT_SESSION.LAST_UPDATED IS '마지막 업데이트 시간';

-- Indexes
CREATE UNIQUE INDEX PK_CHAT_SESSION
    ON CHAT_SESSION (SESS_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE CHAT_SESSION MODIFY (SESS_TYPE      NOT NULL ENABLE);
ALTER TABLE CHAT_SESSION MODIFY (WORKSPACE_ID   NOT NULL ENABLE);
ALTER TABLE CHAT_SESSION MODIFY (SESS_MEM_UUID  NOT NULL ENABLE);
ALTER TABLE CHAT_SESSION ADD CHECK (IS_EMERGENCY IN ('Y', 'N')) ENABLE;
ALTER TABLE CHAT_SESSION ADD CHECK (SESS_TYPE      IN ('T', 'V')) ENABLE;
ALTER TABLE CHAT_SESSION ADD CONSTRAINT PK_CHAT_SESSION
    PRIMARY KEY (SESS_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;
ALTER TABLE CHAT_SESSION MODIFY (LAST_UPDATED  NOT NULL ENABLE);
ALTER TABLE CHAT_SESSION MODIFY (SESS_STARTED_AT NOT NULL ENABLE);
ALTER TABLE CHAT_SESSION MODIFY (IS_EMERGENCY NOT NULL ENABLE);
ALTER TABLE CHAT_SESSION MODIFY (SESS_STATUS   NOT NULL ENABLE);
ALTER TABLE CHAT_SESSION MODIFY (SESS_ID       NOT NULL ENABLE);

-- Foreign Key Constraints
ALTER TABLE CHAT_SESSION
    ADD CONSTRAINT FK_CHAT_SESSION_WORKSPACE
        FOREIGN KEY (WORKSPACE_ID) REFERENCES CHAT_WORKSPACE (WORKSPACE_ID) ENABLE;
ALTER TABLE CHAT_SESSION
    ADD CONSTRAINT FK_CHAT_SESSION_MEMBER
        FOREIGN KEY (SESS_MEM_UUID) REFERENCES MEMBER (MEM_UUID) ENABLE;


--------------------------------------------------------
--  Table: CHAT_WORKSPACE
--------------------------------------------------------
-- Create Table
CREATE TABLE CHAT_WORKSPACE (
                                WORKSPACE_ID       VARCHAR2(100 BYTE),
                                WORKSPACE_NAME     VARCHAR2(100 BYTE),
                                WORKSPACE_CREATED_AT TIMESTAMP (6),
                                WORKSPACE_UPDATED_AT TIMESTAMP (6),
                                WORKSPACE_MEM_UUID VARCHAR2(100 BYTE),
                                WORKSPACE_DELETED_AT TIMESTAMP (6),
                                WORKSPACE_STATUS   VARCHAR2(20 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN CHAT_WORKSPACE.WORKSPACE_ID IS '워크스페이스 고유 ID';
COMMENT ON COLUMN CHAT_WORKSPACE.WORKSPACE_NAME IS '워크스페이스 이름';
COMMENT ON COLUMN CHAT_WORKSPACE.WORKSPACE_CREATED_AT IS '생성일시';
COMMENT ON COLUMN CHAT_WORKSPACE.WORKSPACE_UPDATED_AT IS '수정일시';
COMMENT ON COLUMN CHAT_WORKSPACE.WORKSPACE_MEM_UUID IS '워크스페이스 주인 UUID (MEMBER 테이블의 PK 참조)';
COMMENT ON COLUMN CHAT_WORKSPACE.WORKSPACE_DELETED_AT IS '삭제일시';
COMMENT ON COLUMN CHAT_WORKSPACE.WORKSPACE_STATUS IS '상태 (ACTIVE, ARCHIVED, DELETED)';

-- Indexes
CREATE UNIQUE INDEX PK_CHAT_WORKSPACE
    ON CHAT_WORKSPACE (WORKSPACE_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE CHAT_WORKSPACE MODIFY (WORKSPACE_ID      NOT NULL ENABLE);
ALTER TABLE CHAT_WORKSPACE MODIFY (WORKSPACE_NAME    NOT NULL ENABLE);
ALTER TABLE CHAT_WORKSPACE MODIFY (WORKSPACE_CREATED_AT NOT NULL ENABLE);
ALTER TABLE CHAT_WORKSPACE MODIFY (WORKSPACE_MEM_UUID  NOT NULL ENABLE);
ALTER TABLE CHAT_WORKSPACE MODIFY (WORKSPACE_STATUS  NOT NULL ENABLE);
ALTER TABLE CHAT_WORKSPACE ADD CONSTRAINT PK_CHAT_WORKSPACE
    PRIMARY KEY (WORKSPACE_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE CHAT_WORKSPACE
    ADD CONSTRAINT FK_CHAT_WORKSPACE_MEMBER
        FOREIGN KEY (WORKSPACE_MEM_UUID) REFERENCES MEMBER (MEM_UUID) ENABLE;


--------------------------------------------------------
--  Table: DASHBOARD
--------------------------------------------------------
-- Create Table
CREATE TABLE DASHBOARD (
                           TASK_ID      VARCHAR2(100 BYTE),
                           TASK_CONTENT VARCHAR2(1000 BYTE),
                           TASK_STATUS  CHAR(1 BYTE),
    TASK_DATE    TIMESTAMP (6),
    MEM_UUID     VARCHAR2(100 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN DASHBOARD.TASK_ID IS '할 일 고유 식별자';
COMMENT ON COLUMN DASHBOARD.TASK_CONTENT IS '할 일 내용';
COMMENT ON COLUMN DASHBOARD.TASK_STATUS IS '할 일 상태';
COMMENT ON COLUMN DASHBOARD.TASK_DATE IS '할 일 생성날짜';
COMMENT ON COLUMN DASHBOARD.MEM_UUID IS '작성자';

-- Indexes
CREATE UNIQUE INDEX PK_TASK_ID
    ON DASHBOARD (TASK_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE DASHBOARD MODIFY (TASK_CONTENT NOT NULL ENABLE);
ALTER TABLE DASHBOARD MODIFY (TASK_STATUS  NOT NULL ENABLE);
ALTER TABLE DASHBOARD MODIFY (TASK_DATE    NOT NULL ENABLE);
ALTER TABLE DASHBOARD MODIFY (MEM_UUID     NOT NULL ENABLE);
ALTER TABLE DASHBOARD ADD CONSTRAINT PK_TASK_ID
    PRIMARY KEY (TASK_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE DASHBOARD
    ADD CONSTRAINT FK_MEM_UUID
        FOREIGN KEY (MEM_UUID) REFERENCES MEMBER (MEM_UUID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  Table: DOC_FILE
--------------------------------------------------------
-- Create Table
CREATE TABLE DOC_FILE (
                          DF_ID             VARCHAR2(100 BYTE),
                          DF_ORIGINALNAME   VARCHAR2(1000 BYTE),
                          DF_RENAME         VARCHAR2(1000 BYTE),
                          DOC_ID            VARCHAR2(100 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN DOC_FILE.DF_ID IS '첨부파일 고유 ID';
COMMENT ON COLUMN DOC_FILE.DF_ORIGINALNAME IS '공문서 원본파일명';
COMMENT ON COLUMN DOC_FILE.DF_RENAME IS '공문서 저장파일명';
COMMENT ON COLUMN DOC_FILE.DOC_ID IS '공문서ID';

-- Indexes
CREATE UNIQUE INDEX PK_DF_ID
    ON DOC_FILE (DF_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE DOC_FILE MODIFY (DF_ORIGINALNAME NOT NULL ENABLE);
ALTER TABLE DOC_FILE MODIFY (DF_RENAME       NOT NULL ENABLE);
ALTER TABLE DOC_FILE MODIFY (DOC_ID          NOT NULL ENABLE);
ALTER TABLE DOC_FILE ADD CONSTRAINT PK_DF_ID
    PRIMARY KEY (DF_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE DOC_FILE
    ADD CONSTRAINT FK_DF_DOC_ID
        FOREIGN KEY (DOC_ID) REFERENCES DOCUMENT (DOC_ID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  Table: DOCUMENT
--------------------------------------------------------
-- Create Table
CREATE TABLE DOCUMENT (
                          DOC_ID            VARCHAR2(100 BYTE),
                          DOC_TYPE          VARCHAR2(200 BYTE),
                          IS_APPROVED       VARCHAR2(20 BYTE) DEFAULT '대기중',
                          DOC_COMPLETED_AT  TIMESTAMP (6),
                          WRITTEN_BY        VARCHAR2(36 BYTE),
                          APPROVED_BY       VARCHAR2(36 BYTE),
                          APPROVED_AT       TIMESTAMP (6),
                          SUBMITTED_AT      TIMESTAMP (6)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN DOCUMENT.DOC_ID IS '공문서 고유ID';
COMMENT ON COLUMN DOCUMENT.DOC_TYPE IS '공문서 종류';
COMMENT ON COLUMN DOCUMENT.IS_APPROVED IS '승인상태';
COMMENT ON COLUMN DOCUMENT.DOC_COMPLETED_AT IS '공문서 작성 완료 날짜';
COMMENT ON COLUMN DOCUMENT.WRITTEN_BY IS '작성한 노인 UUID';
COMMENT ON COLUMN DOCUMENT.APPROVED_BY IS '승인할 담당자 UUID';
COMMENT ON COLUMN DOCUMENT.APPROVED_AT IS '담당자의 승인날짜';
COMMENT ON COLUMN DOCUMENT.SUBMITTED_AT IS '공문서 제출날짜';

-- Indexes
CREATE UNIQUE INDEX PK_DOC_ID
    ON DOCUMENT (DOC_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE DOCUMENT MODIFY (WRITTEN_BY NOT NULL ENABLE);
ALTER TABLE DOCUMENT MODIFY (DOC_TYPE   NOT NULL ENABLE);
ALTER TABLE DOCUMENT ADD CONSTRAINT PK_DOC_ID
    PRIMARY KEY (DOC_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;


--------------------------------------------------------
--  Table: EMERGENCY_LOG
--------------------------------------------------------
-- Create Table
CREATE TABLE EMERGENCY_LOG (
                               EMG_LOG_ID            VARCHAR2(100 BYTE),
                               EMG_DETECTED_MOTION     VARCHAR2(255 BYTE),
                               EMG_CAP_PATH          VARCHAR2(255 BYTE),
                               EMG_ALERT_SENT_TO     VARCHAR2(255 BYTE),
                               EMG_CREATED_AT        TIMESTAMP (6),
                               EMG_USER_UUID         VARCHAR2(100 BYTE),
                               EMG_CANCEL            CHAR(1 BYTE) DEFAULT 'N',
    EMG_CANCLE_AT         TIMESTAMP (6),
    EMG_F_PHONE           VARCHAR2(100 BYTE),
    EMG_S_PHONE           VARCHAR2(100 BYTE),
    EMG_SESS_ID           VARCHAR2(100 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN EMERGENCY_LOG.EMG_LOG_ID IS '긴급 상황 고유 ID';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_DETECTED_MOTION IS '감지된 모션';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_CAP_PATH IS '캡쳐된 이미지 경로';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_ALERT_SENT_TO IS '알림 발송 대상';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_CREATED_AT IS '긴급 상황 발생 시간';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_USER_UUID IS '긴급상황 대상유저';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_CANCEL IS '취소여부';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_CANCLE_AT IS '취소시간';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_F_PHONE IS '보호자연락처';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_S_PHONE IS '보호소연락처';
COMMENT ON COLUMN EMERGENCY_LOG.EMG_SESS_ID IS '메시지 고유 ID';

-- Indexes
CREATE UNIQUE INDEX PK_EMG_LOG_ID
    ON EMERGENCY_LOG (EMG_LOG_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE EMERGENCY_LOG MODIFY (EMG_ALERT_SENT_TO NOT NULL ENABLE);
ALTER TABLE EMERGENCY_LOG MODIFY (EMG_CREATED_AT     NOT NULL ENABLE);
ALTER TABLE EMERGENCY_LOG MODIFY (EMG_USER_UUID      NOT NULL ENABLE);
ALTER TABLE EMERGENCY_LOG MODIFY (EMG_CANCEL         NOT NULL ENABLE);
ALTER TABLE EMERGENCY_LOG MODIFY (EMG_F_PHONE        NOT NULL ENABLE);
ALTER TABLE EMERGENCY_LOG MODIFY (EMG_S_PHONE        NOT NULL ENABLE);
ALTER TABLE EMERGENCY_LOG MODIFY (EMG_SESS_ID        NOT NULL ENABLE);
ALTER TABLE EMERGENCY_LOG ADD CHECK (EMG_CANCEL IN ('Y','N')) ENABLE;
ALTER TABLE EMERGENCY_LOG ADD CONSTRAINT PK_EMG_LOG_ID
    PRIMARY KEY (EMG_LOG_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE EMERGENCY_LOG
    ADD CONSTRAINT FK_EMG_USER_UUID
        FOREIGN KEY (EMG_USER_UUID) REFERENCES MEMBER (MEM_UUID)
            ON DELETE CASCADE ENABLE;
ALTER TABLE EMERGENCY_LOG
    ADD CONSTRAINT FK_EMERGENCY_LOG_SESS_ID
        FOREIGN KEY (EMG_SESS_ID) REFERENCES CHAT_SESSION (SESS_ID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  Table: FAQ
--------------------------------------------------------
-- Create Table
CREATE TABLE FAQ (
                     FAQ_ID         VARCHAR2(100 BYTE),
                     FAQ_TITLE      VARCHAR2(250 BYTE),
                     FAQ_CREATED_AT TIMESTAMP (6) DEFAULT SYSDATE,
                     FAQ_UPDATED_AT TIMESTAMP (6) DEFAULT SYSDATE,
                     FAQ_CONTENT    CLOB,
                     FAQ_CREATED_BY VARCHAR2(100 BYTE),
                     FAQ_UPDATED_BY VARCHAR2(100 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS
LOB (FAQ_CONTENT) STORE AS SECUREFILE (
    TABLESPACE USERS,
    ENABLE STORAGE IN ROW,
    CHUNK 8192,
    NOCACHE,
    LOGGING,
    NOCOMPRESS,
    KEEP_DUPLICATES,
    STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
);

-- Column Comments
COMMENT ON COLUMN FAQ.FAQ_ID IS 'FAQ식별코드';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS '제목';
COMMENT ON COLUMN FAQ.FAQ_CREATED_AT IS '질문 등록 날짜';
COMMENT ON COLUMN FAQ.FAQ_UPDATED_AT IS '질문 수정 날짜';
COMMENT ON COLUMN FAQ.FAQ_CONTENT IS '질문내용';
COMMENT ON COLUMN FAQ.FAQ_CREATED_BY IS '질문자';
COMMENT ON COLUMN FAQ.FAQ_UPDATED_BY IS '질문자(수정)';

-- Indexes
CREATE UNIQUE INDEX PK_FAQ_ID
    ON FAQ (FAQ_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE FAQ MODIFY (FAQ_TITLE      NOT NULL ENABLE);
ALTER TABLE FAQ MODIFY (FAQ_CREATED_AT NOT NULL ENABLE);
ALTER TABLE FAQ MODIFY (FAQ_UPDATED_AT NOT NULL ENABLE);
ALTER TABLE FAQ MODIFY (FAQ_CONTENT    NOT NULL ENABLE);
ALTER TABLE FAQ ADD CONSTRAINT PK_FAQ_ID
    PRIMARY KEY (FAQ_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE FAQ
    ADD CONSTRAINT FK_FAQ_CREATED_BY
        FOREIGN KEY (FAQ_CREATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;
ALTER TABLE FAQ
    ADD CONSTRAINT FK_FAQ_UPDATED_BY
        FOREIGN KEY (FAQ_UPDATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;




--------------------------------------------------------
--  Table: MEDICAL
--------------------------------------------------------
-- Create Table
CREATE TABLE MEDICAL (
                         MEDI_ID             VARCHAR2(100 BYTE),
                         MEDI_DIAG_DATE      TIMESTAMP (6),
                         MEDI_DISEASE_NAME   VARCHAR2(255 BYTE),
                         MEDI_LAST_TREAT_DATE TIMESTAMP (6),
                         MEDI_PRIVACY        CHAR(1 BYTE),
    MEDI_CREATED_AT     TIMESTAMP (6) DEFAULT SYSDATE,
    MEDI_UPDATED_AT     TIMESTAMP (6),
    MEDI_SNR_UUID       VARCHAR2(100 BYTE),
    MEDI_MGR_UUID       VARCHAR2(100 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN MEDICAL.MEDI_ID IS '병력 고유 식별자 ID';
COMMENT ON COLUMN MEDICAL.MEDI_DIAG_DATE IS '진단일';
COMMENT ON COLUMN MEDICAL.MEDI_DISEASE_NAME IS '병명';
COMMENT ON COLUMN MEDICAL.MEDI_LAST_TREAT_DATE IS '최근진료일자';
COMMENT ON COLUMN MEDICAL.MEDI_PRIVACY IS '가족공개여부 (T/F)';
COMMENT ON COLUMN MEDICAL.MEDI_CREATED_AT IS '병력 생성시간';
COMMENT ON COLUMN MEDICAL.MEDI_UPDATED_AT IS '병력 수정시간';
COMMENT ON COLUMN MEDICAL.MEDI_SNR_UUID IS '노인 사용자 UUID (MEMBER 테이블 참조)';
COMMENT ON COLUMN MEDICAL.MEDI_MGR_UUID IS '담당자 UUID (MEMBER 테이블 참조)';

-- Indexes
CREATE UNIQUE INDEX PK_MEDICAL
    ON MEDICAL (MEDI_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE MEDICAL MODIFY (MEDI_ID             NOT NULL ENABLE);
ALTER TABLE MEDICAL MODIFY (MEDI_DIAG_DATE      NOT NULL ENABLE);
ALTER TABLE MEDICAL MODIFY (MEDI_DISEASE_NAME   NOT NULL ENABLE);
ALTER TABLE MEDICAL MODIFY (MEDI_LAST_TREAT_DATE NOT NULL ENABLE);
ALTER TABLE MEDICAL MODIFY (MEDI_PRIVACY        NOT NULL ENABLE);
ALTER TABLE MEDICAL MODIFY (MEDI_CREATED_AT     NOT NULL ENABLE);
ALTER TABLE MEDICAL MODIFY (MEDI_SNR_UUID       NOT NULL ENABLE);
ALTER TABLE MEDICAL MODIFY (MEDI_MGR_UUID       NOT NULL ENABLE);
ALTER TABLE MEDICAL ADD CONSTRAINT PK_MEDICAL
    PRIMARY KEY (MEDI_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE MEDICAL
    ADD CONSTRAINT FK_MEDI_SNR_UUID
        FOREIGN KEY (MEDI_SNR_UUID) REFERENCES MEMBER (MEM_UUID) ENABLE;
ALTER TABLE MEDICAL
    ADD CONSTRAINT FK_MEDI_MGR_UUID
        FOREIGN KEY (MEDI_MGR_UUID) REFERENCES MEMBER (MEM_UUID) ENABLE;


--------------------------------------------------------
--  Table: MEMBER
--------------------------------------------------------
-- Create Table
CREATE TABLE MEMBER (
                        MEM_UUID           VARCHAR2(100)		CONSTRAINT PK_MEM_UUID PRIMARY KEY,
                        MEM_ID          	VARCHAR2(50)		,
                        MEM_PW          	VARCHAR2(200)		NOT NULL,
                        MEM_NAME        	VARCHAR2(50)		NOT NULL,
                        MEM_TYPE        	VARCHAR2(30)		CONSTRAINT CHK_MEM_TYPE CHECK (MEM_TYPE IN ('SENIOR', 'MANAGER', 'FAMILY', 'ADMIN','AI')) NOT NULL,
                        MEM_EMAIL       	VARCHAR2(50)		,
                        MEM_ADDRESS     	VARCHAR2(300)		NOT NULL,
                        MEM_CELLPHONE   	VARCHAR2(50)		,
                        MEM_PHONE	        VARCHAR2(50)		,
                        MEM_RNN	            VARCHAR2(50)		NOT NULL,
                        MEM_ORG_NAME	    VARCHAR2(200)		,
                        MEM_STATUS	        VARCHAR2(50)		DEFAULT 'ACTIVE' CONSTRAINT CHK_MEM_STATUS CHECK (MEM_STATUS IN ('ACTIVE', 'BLOCKED', 'INACTIVE', 'REMOVED')) NOT NULL,
                        MEM_ENROLL_DATE	    TIMESTAMP		    DEFAULT SYSDATE NOT NULL,
                        MEM_CHANGE_STATUS	TIMESTAMP		    DEFAULT SYSDATE,
                        MEM_FAMILY_APPROVAL VARCHAR2(100)             DEFAULT 'N/A' CONSTRAINT CHK_MEM_FAMILY_APPROVAL CHECK (MEM_FAMILY_APPROVAL IN ('APPROVED', 'PENDING', 'REJECTED', 'N/A')),
                        MEM_SOCIAL_KAKAO	CHAR(1)		        DEFAULT 'N',
                        MEM_KAKAO_PI	    VARCHAR2(200)		,
                        MEM_SOCIAL_NAVER	CHAR(1)		        DEFAULT 'N',
                        MEM_NAVER_PI	    VARCHAR2(200)		,
                        MEM_SOCIAL_GOOGLE	CHAR(1)		        DEFAULT 'N',
                        MEM_GOOGLE_PI	VARCHAR2(200)		,
                        MEM_UUID_FAM	    VARCHAR2(100)		,
                        MEM_UUID_MGR	    VARCHAR2(100)		,
                        MEM_SEN_FAM_RELATIONSHIP	VARCHAR2(200)		CONSTRAINT CHK_MEM_RELATIONSHIP CHECK (MEM_SEN_FAM_RELATIONSHIP IN ('CHILD', 'BROSIS', 'PARTNER', 'BRIDE', 'GROOM')),
                        MEM_SENIOR_PROFILE		VARCHAR2(300),
);

SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN MEMBER.MEM_UUID IS '회원 고유 식별자';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEM_PW IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEM_TYPE IS '회원 타입';
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBER.MEM_ADDRESS IS '회원 주소(담당자의 경우 기관주소)';
COMMENT ON COLUMN MEMBER.MEM_CELLPHONE IS '휴대전화번호';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '일반전화번호(담당자의 경우 기관전화번호)';
COMMENT ON COLUMN MEMBER.MEM_RNN IS '주민등록번호';
COMMENT ON COLUMN MEMBER.MEM_ORG_NAME IS '기관명';
COMMENT ON COLUMN MEMBER.MEM_STATUS IS '회원 상태';
COMMENT ON COLUMN MEMBER.MEM_ENROLL_DATE IS '가입일자';
COMMENT ON COLUMN MEMBER.MEM_CHANGE_STATUS IS '회원상태변경일자';
COMMENT ON COLUMN MEMBER.MEM_FAMILY_APPROVAL IS '가족계정 승인여부(어르신 계정에만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_SOCIAL_KAKAO IS '소셜연동 KAKAO(가족계정만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_KAKAO_PI IS 'KAKAO 소셜 고유 ID(가족계정만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_SOCIAL_NAVER IS '소셜연동 NAVER(가족계정만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_NAVER_PI IS 'NAVER 소셜 고유 ID(가족계정만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_SOCIAL_GOOGLE IS '소셜연동 GOOGLE(가족계정만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_GOOGLE_PI IS 'GOOGLE 소셜 고유 ID(가족계정만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_UUID_FAM IS '가족 고유 식별자(어르신 계정에만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_UUID_MGR IS '담당자 고유 식별자(어르신 계정에만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_SEN_FAM_RELATIONSHIP IS '어르신과 가족간의 관계 정보(어르신 계정에만 해당하는 컬럼)';
COMMENT ON COLUMN MEMBER.MEM_SENIOR_PROFILE IS '어르신 프로필 사진 원본 이름';

-- Table Constraints (ALTER TABLE)
ALTER TABLE MEMBER
    ADD CONSTRAINT CHK_MEM_FAMILY_APPROVAL
        CHECK (MEM_FAMILY_APPROVAL IN ('APPROVED', 'PENDING', 'REJECTED', 'N/A')) ENABLE;
ALTER TABLE MEMBER MODIFY (MEM_PW       NOT NULL ENABLE);
ALTER TABLE MEMBER MODIFY (MEM_NAME     NOT NULL ENABLE);
ALTER TABLE MEMBER MODIFY (MEM_TYPE     NOT NULL ENABLE);
ALTER TABLE MEMBER MODIFY (MEM_ADDRESS  NOT NULL ENABLE);
ALTER TABLE MEMBER MODIFY (MEM_RNN      NOT NULL ENABLE);
ALTER TABLE MEMBER MODIFY (MEM_STATUS   NOT NULL ENABLE);
ALTER TABLE MEMBER MODIFY (MEM_ENROLL_DATE NOT NULL ENABLE);
ALTER TABLE MEMBER ADD CONSTRAINT CHK_MEM_TYPE
    CHECK (MEM_TYPE IN ('SENIOR', 'MANAGER', 'FAMILY', 'ADMIN')) ENABLE;
ALTER TABLE MEMBER ADD CONSTRAINT CHK_MEM_STATUS
    CHECK (MEM_STATUS IN ('ACTIVE', 'BLOCKED', 'INACTIVE', 'REMOVED')) ENABLE;
ALTER TABLE MEMBER ADD CONSTRAINT PK_MEM_UUID
    PRIMARY KEY (MEM_UUID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;


--------------------------------------------------------
--  Table: MEMBER_FILES
--------------------------------------------------------
-- Create Table
CREATE TABLE MEMBER_FILES (
                              MF_ID            VARCHAR2(100 BYTE),
                              MF_MEM_UUID      VARCHAR2(100 BYTE),
                              MF_ORIGINAL_NAME VARCHAR2(1000 BYTE),
                              MF_RENAME        VARCHAR2(1000 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN MEMBER_FILES.MF_ID IS '첨부파일 고유 ID';
COMMENT ON COLUMN MEMBER_FILES.MF_MEM_UUID IS '회원 고유 식별자';
COMMENT ON COLUMN MEMBER_FILES.MF_ORIGINAL_NAME IS '원본 파일이름';
COMMENT ON COLUMN MEMBER_FILES.MF_RENAME IS '저장용 파일이름';

-- Indexes
CREATE UNIQUE INDEX PK_MF_ID
    ON MEMBER_FILES (MF_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE MEMBER_FILES MODIFY (MF_MEM_UUID      NOT NULL ENABLE);
ALTER TABLE MEMBER_FILES MODIFY (MF_ORIGINAL_NAME NOT NULL ENABLE);
ALTER TABLE MEMBER_FILES MODIFY (MF_RENAME        NOT NULL ENABLE);
ALTER TABLE MEMBER_FILES ADD CONSTRAINT PK_MF_ID
    PRIMARY KEY (MF_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE MEMBER_FILES
    ADD CONSTRAINT FK_MF_MEM_UUID
        FOREIGN KEY (MF_MEM_UUID) REFERENCES MEMBER (MEM_UUID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  Table: NOTICE
--------------------------------------------------------
-- Create Table
CREATE TABLE NOTICE (
                        NOT_ID           VARCHAR2(100 BYTE),
                        NOT_TITLE        VARCHAR2(250 BYTE),
                        NOT_CONTENT      CLOB,
                        NOT_CREATED_AT   TIMESTAMP (6) DEFAULT SYSDATE,
                        NOT_CREATED_BY   VARCHAR2(100 BYTE),
                        NOT_UPDATED_AT   TIMESTAMP (6) DEFAULT SYSDATE,
                        NOT_UPDATED_BY   VARCHAR2(100 BYTE),
                        NOT_DELETED_AT   TIMESTAMP (6),
                        NOT_DELETED_BY   VARCHAR2(100 BYTE),
                        NOT_READ_COUNT   NUMBER
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS
LOB (NOT_CONTENT) STORE AS SECUREFILE (
    TABLESPACE USERS,
    ENABLE STORAGE IN ROW,
    CHUNK 8192,
    NOCACHE,
    LOGGING,
    NOCOMPRESS,
    KEEP_DUPLICATES,
    STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
);

-- Column Comments
COMMENT ON COLUMN NOTICE.NOT_ID IS '공지사항 고유 ID';
COMMENT ON COLUMN NOTICE.NOT_TITLE IS '제목';
COMMENT ON COLUMN NOTICE.NOT_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.NOT_CREATED_AT IS '등록일';
COMMENT ON COLUMN NOTICE.NOT_CREATED_BY IS '등록자';
COMMENT ON COLUMN NOTICE.NOT_UPDATED_AT IS '수정일';
COMMENT ON COLUMN NOTICE.NOT_UPDATED_BY IS '수정자';
COMMENT ON COLUMN NOTICE.NOT_DELETED_AT IS '삭제일';
COMMENT ON COLUMN NOTICE.NOT_DELETED_BY IS '삭제자';
COMMENT ON COLUMN NOTICE.NOT_READ_COUNT IS '조회수';

-- Indexes
CREATE UNIQUE INDEX PK_NOT_ID
    ON NOTICE (NOT_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE NOTICE MODIFY (NOT_TITLE       NOT NULL ENABLE);
ALTER TABLE NOTICE MODIFY (NOT_CONTENT     NOT NULL ENABLE);
ALTER TABLE NOTICE MODIFY (NOT_CREATED_AT  NOT NULL ENABLE);
ALTER TABLE NOTICE MODIFY (NOT_UPDATED_AT  NOT NULL ENABLE);
ALTER TABLE NOTICE MODIFY (NOT_READ_COUNT  NOT NULL ENABLE);
ALTER TABLE NOTICE ADD CONSTRAINT PK_NOT_ID
    PRIMARY KEY (NOT_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
                FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE NOTICE
    ADD CONSTRAINT FK_NOT_CREATED_BY
        FOREIGN KEY (NOT_CREATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;
ALTER TABLE NOTICE
    ADD CONSTRAINT FK_NOT_UPDATED_BY
        FOREIGN KEY (NOT_UPDATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;
ALTER TABLE NOTICE
    ADD CONSTRAINT FK_NOT_DELETED_BY
        FOREIGN KEY (NOT_DELETED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;


--------------------------------------------------------
--  Table: NOTICE_FILES
--------------------------------------------------------
-- Create Table
CREATE TABLE NOTICE_FILES (
                              NF_ID             VARCHAR2(100 BYTE),
                              NF_NOT_ID         VARCHAR2(100 BYTE),
                              NF_ORIGINAL_NAME  VARCHAR2(1000 BYTE),
                              NF_RENAME         VARCHAR2(1000 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN NOTICE_FILES.NF_ID IS '첨부파일 고유 ID';
COMMENT ON COLUMN NOTICE_FILES.NF_NOT_ID IS '공지사항 고유 ID';
COMMENT ON COLUMN NOTICE_FILES.NF_ORIGINAL_NAME IS '원본 파일이름';
COMMENT ON COLUMN NOTICE_FILES.NF_RENAME IS '저장용 파일이름';

-- Indexes
CREATE UNIQUE INDEX PK_NF_ID
    ON NOTICE_FILES (NF_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE NOTICE_FILES MODIFY (NF_NOT_ID         NOT NULL ENABLE);
ALTER TABLE NOTICE_FILES MODIFY (NF_ORIGINAL_NAME  NOT NULL ENABLE);
ALTER TABLE NOTICE_FILES MODIFY (NF_RENAME         NOT NULL ENABLE);
ALTER TABLE NOTICE_FILES ADD CONSTRAINT PK_NF_ID
    PRIMARY KEY (NF_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE NOTICE_FILES
    ADD CONSTRAINT FK_NF_NOT_ID
        FOREIGN KEY (NF_NOT_ID) REFERENCES NOTICE (NOT_ID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  Table: QNA
--------------------------------------------------------
-- Create Table
CREATE TABLE QNA (
                     QNA_ID            VARCHAR2(100 BYTE),
                     QNA_TITLE         VARCHAR2(250 BYTE),
                     QNA_W_CREATED_AT  TIMESTAMP (6) DEFAULT SYSDATE,
                     QNA_W_UPDATED_AT  TIMESTAMP (6) DEFAULT SYSDATE,
                     QNA_W_CONTENT     CLOB,
                     QNA_W_CREATED_BY  VARCHAR2(100 BYTE),
                     QNA_AD_CREATED_AT TIMESTAMP (6),
                     QNA_AD_UPDATED_AT TIMESTAMP (6),
                     QNA_AD_CONTENT    CLOB,
                     QNA_AD_CREATED_BY VARCHAR2(100 BYTE),
                     QNA_AD_UPDATED_BY VARCHAR2(100 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS
LOB (QNA_W_CONTENT) STORE AS SECUREFILE (
    TABLESPACE USERS,
    ENABLE STORAGE IN ROW,
    CHUNK 8192,
    NOCACHE,
    LOGGING,
    NOCOMPRESS,
    KEEP_DUPLICATES,
    STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
)
LOB (QNA_AD_CONTENT) STORE AS SECUREFILE (
    TABLESPACE USERS,
    ENABLE STORAGE IN ROW,
    CHUNK 8192,
    NOCACHE,
    LOGGING,
    NOCOMPRESS,
    KEEP_DUPLICATES,
    STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
);

-- Column Comments
COMMENT ON COLUMN QNA.QNA_ID IS 'QNA식별코드';
COMMENT ON COLUMN QNA.QNA_TITLE IS '제목';
COMMENT ON COLUMN QNA.QNA_W_CREATED_AT IS '질문 등록 날짜';
COMMENT ON COLUMN QNA.QNA_W_UPDATED_AT IS '질문 수정 날짜';
COMMENT ON COLUMN QNA.QNA_W_CONTENT IS '질문내용';
COMMENT ON COLUMN QNA.QNA_W_CREATED_BY IS '질문자';
COMMENT ON COLUMN QNA.QNA_AD_CREATED_AT IS '답변 등록 날짜';
COMMENT ON COLUMN QNA.QNA_AD_UPDATED_AT IS '답변 수정 날짜';
COMMENT ON COLUMN QNA.QNA_AD_CONTENT IS '답변내용';
COMMENT ON COLUMN QNA.QNA_AD_CREATED_BY IS '답변자';
COMMENT ON COLUMN QNA.QNA_AD_UPDATED_BY IS '답변자(수정)';

-- Indexes
CREATE UNIQUE INDEX PK_QNA_ID
    ON QNA (QNA_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE QNA MODIFY (QNA_TITLE        NOT NULL ENABLE);
ALTER TABLE QNA MODIFY (QNA_W_CREATED_AT  NOT NULL ENABLE);
ALTER TABLE QNA MODIFY (QNA_W_UPDATED_AT  NOT NULL ENABLE);
ALTER TABLE QNA MODIFY (QNA_W_CONTENT     NOT NULL ENABLE);
ALTER TABLE QNA MODIFY (QNA_W_CREATED_BY  NOT NULL ENABLE);
ALTER TABLE QNA ADD CONSTRAINT PK_QNA_ID
    PRIMARY KEY (QNA_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE QNA
    ADD CONSTRAINT FK_QNA_W_CREATED_BY
        FOREIGN KEY (QNA_W_CREATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE CASCADE ENABLE;
ALTER TABLE QNA
    ADD CONSTRAINT FK_QNA_AD_CREATED_BY
        FOREIGN KEY (QNA_AD_CREATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;
ALTER TABLE QNA
    ADD CONSTRAINT FK_QNA_AD_UPDATED_BY
        FOREIGN KEY (QNA_AD_UPDATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;


--------------------------------------------------------
--  Table: REFRESH_TOKEN
--------------------------------------------------------
-- Create Table
CREATE TABLE REFRESH_TOKEN (
                               TOKEN_UUID      VARCHAR2(100 BYTE),
                               TOKEN_MEM_UUID  VARCHAR2(100 BYTE),
                               TOKEN_VALUE     VARCHAR2(2000 BYTE),
                               TOKEN_CREATED_AT TIMESTAMP (6) DEFAULT SYSDATE,
                               TOKEN_EXP_IN    NUMBER,
                               TOKEN_EXP_DATE  TIMESTAMP (6),
                               TOKEN_STATUS    VARCHAR2(50 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN REFRESH_TOKEN.TOKEN_UUID IS '토큰고유 식별자';
COMMENT ON COLUMN REFRESH_TOKEN.TOKEN_MEM_UUID IS '회원 고유 식별자';
COMMENT ON COLUMN REFRESH_TOKEN.TOKEN_VALUE IS '토큰값';
COMMENT ON COLUMN REFRESH_TOKEN.TOKEN_CREATED_AT IS '토큰생성일자';
COMMENT ON COLUMN REFRESH_TOKEN.TOKEN_EXP_IN IS '토큰만료설정값';
COMMENT ON COLUMN REFRESH_TOKEN.TOKEN_EXP_DATE IS '토큰만료일자';
COMMENT ON COLUMN REFRESH_TOKEN.TOKEN_STATUS IS '토큰상태';

-- Indexes
CREATE UNIQUE INDEX PK_TOKEN_UUID
    ON REFRESH_TOKEN (TOKEN_UUID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE REFRESH_TOKEN MODIFY (TOKEN_MEM_UUID NOT NULL ENABLE);
ALTER TABLE REFRESH_TOKEN MODIFY (TOKEN_VALUE    NOT NULL ENABLE);
ALTER TABLE REFRESH_TOKEN MODIFY (TOKEN_EXP_IN   NOT NULL ENABLE);
ALTER TABLE REFRESH_TOKEN MODIFY (TOKEN_EXP_DATE NOT NULL ENABLE);
ALTER TABLE REFRESH_TOKEN ADD CONSTRAINT PK_TOKEN_UUID
    PRIMARY KEY (TOKEN_UUID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE REFRESH_TOKEN
    ADD CONSTRAINT FK_TOKEN_MEM_UUID
        FOREIGN KEY (TOKEN_MEM_UUID) REFERENCES MEMBER (MEM_UUID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  Table: SENIOR_PROGRAM
--------------------------------------------------------
-- Create Table
CREATE TABLE SENIOR_PROGRAM (
                                SNR_PROGRAM_ID  VARCHAR2(100 BYTE),
                                SNR_TITLE       VARCHAR2(255 BYTE),
                                SNR_CONTENT     CLOB,
                                SNR_STARTED_AT  TIMESTAMP (6),
                                SNR_ENDED_AT    TIMESTAMP (6),
                                SNR_ORG_NAME    VARCHAR2(255 BYTE),
                                SNR_ORG_PHONE   VARCHAR2(25 BYTE),
                                SNR_MGR_EMAIL   VARCHAR2(255 BYTE),
                                SNR_CREATED_AT  TIMESTAMP (6) DEFAULT SYSDATE,
                                SNR_UPDATED_AT  TIMESTAMP (6),
                                SNR_MGR_NAME    VARCHAR2(50 BYTE),
                                SNR_UPDATED_BY  VARCHAR2(50 BYTE),
                                SNR_CREATED_BY  VARCHAR2(50 BYTE),
                                SNR_ORG_ADDRESS VARCHAR2(255 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS
LOB (SNR_CONTENT) STORE AS SECUREFILE (
    TABLESPACE USERS,
    ENABLE STORAGE IN ROW,
    CHUNK 8192,
    NOCACHE,
    LOGGING,
    NOCOMPRESS,
    KEEP_DUPLICATES,
    STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
);

-- Column Comments
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_PROGRAM_ID  IS '프로그램 고유 식별자';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_TITLE       IS '프로그램 제목';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_CONTENT     IS '프로그램 본문';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_STARTED_AT  IS '참여 시작일';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_ENDED_AT    IS '참여 종료일';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_ORG_NAME    IS '기관명';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_ORG_PHONE   IS '기관 전화번호';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_MGR_EMAIL   IS '담당자 이메일';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_CREATED_AT  IS '등록일시';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_UPDATED_AT  IS '수정일시';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_MGR_NAME    IS '담당자명';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_UPDATED_BY  IS '수정자';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_CREATED_BY  IS '등록자';
COMMENT ON COLUMN SENIOR_PROGRAM.SNR_ORG_ADDRESS IS '주소';

-- Indexes
CREATE UNIQUE INDEX PK_SNR_PROGRAM_ID
    ON SENIOR_PROGRAM (SNR_PROGRAM_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_TITLE       NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_CONTENT     NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_STARTED_AT  NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_ENDED_AT    NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_ORG_NAME    NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_ORG_PHONE   NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_MGR_EMAIL   NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_CREATED_AT  NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_CREATED_BY  NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM MODIFY (SNR_ORG_ADDRESS NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM ADD CONSTRAINT PK_SNR_PROGRAM_ID
    PRIMARY KEY (SNR_PROGRAM_ID)
    USING INDEX
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE SENIOR_PROGRAM
    ADD CONSTRAINT FK_SNR_UPDATED_BY
        FOREIGN KEY (SNR_UPDATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE SET NULL ENABLE;
ALTER TABLE SENIOR_PROGRAM
    ADD CONSTRAINT FK_SNR_CREATED_BY
        FOREIGN KEY (SNR_CREATED_BY) REFERENCES MEMBER (MEM_UUID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  Table: SENIOR_PROGRAM_FILE
--------------------------------------------------------
-- Create Table
CREATE TABLE SENIOR_PROGRAM_FILE (
                                     SNR_FILE_ID    VARCHAR2(100 BYTE),
                                     SNR_FILE_OG_NAME VARCHAR2(1000 BYTE),
                                     SNR_FILE_NAME  VARCHAR2(1000 BYTE),
                                     SNR_PROGRAM_ID VARCHAR2(100 BYTE)
)
    SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE USERS;

-- Column Comments
COMMENT ON COLUMN SENIOR_PROGRAM_FILE.SNR_FILE_ID IS '첨부파일 고유 ID';
COMMENT ON COLUMN SENIOR_PROGRAM_FILE.SNR_FILE_OG_NAME IS '원본 파일이름';
COMMENT ON COLUMN SENIOR_PROGRAM_FILE.SNR_FILE_NAME IS '저장용 파일이름';
COMMENT ON COLUMN SENIOR_PROGRAM_FILE.SNR_PROGRAM_ID IS '프로그램 고유 식별자';

-- Indexes
CREATE UNIQUE INDEX PK_SNR_FILE_ID
    ON SENIOR_PROGRAM_FILE (SNR_FILE_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT 
            FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

-- Table Constraints (ALTER TABLE)
ALTER TABLE SENIOR_PROGRAM_FILE MODIFY (SNR_FILE_OG_NAME NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM_FILE MODIFY (SNR_FILE_NAME   NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM_FILE MODIFY (SNR_PROGRAM_ID  NOT NULL ENABLE);
ALTER TABLE SENIOR_PROGRAM_FILE ADD CONSTRAINT PK_SNR_FILE_ID
    PRIMARY KEY (SNR_FILE_ID)
    USING INDEX 
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE USERS ENABLE;

-- Foreign Key Constraints
ALTER TABLE SENIOR_PROGRAM_FILE
    ADD CONSTRAINT FK_SNR_PROGRAM_ID
        FOREIGN KEY (SNR_PROGRAM_ID) REFERENCES SENIOR_PROGRAM (SNR_PROGRAM_ID)
            ON DELETE CASCADE ENABLE;


--------------------------------------------------------
